runtime: python37
instance_class: F2

handlers:
- url: /api/.*
  script: auto
  secure: always
- url: /assets
  static_dir: static/assets
  secure: always
- url: /static
  static_dir: static
  secure: always
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always
- url: /.*
  static_files: static/index.html
  upload: static/index.html
  secure: always
