const data = [
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221410",
    "ProjectName": "4691 Eget, Road",
    "ClientName": "Phasellus Dolor Elit Industries",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1000971",
    "InvoiceDate": "2018-07-03",
    "InvoiceAmount": 8250,
    "Outstanding30Days": 0,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 8250
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221423",
    "ProjectName": "Abraj Al-Bait Clock Tower",
    "ClientName": "Et Ultrices Posuere Foundation",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "Harte Melegsalot",
    "InvoiceNumber": "1001046",
    "InvoiceDate": "2018-09-05",
    "InvoiceAmount": 82500,
    "Outstanding30Days": 0,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 82500
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "200017",
    "ProjectName": "9468 Ultrices Road",
    "ClientName": "Ligula Eu Corp.",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001076",
    "InvoiceDate": "2018-10-04",
    "InvoiceAmount": 1452.1,
    "Outstanding30Days": 0,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 1452.1
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221423",
    "ProjectName": "Abraj Al-Bait Clock Tower",
    "ClientName": "Et Ultrices Posuere Foundation",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "Harte Melegsalot",
    "InvoiceNumber": "1001079",
    "InvoiceDate": "2018-10-05",
    "InvoiceAmount": 10439,
    "Outstanding30Days": 0,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 10439
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221232",
    "ProjectName": "Bent Pyramid",
    "ClientName": "Phasellus Dolor Elit Industries",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001094",
    "InvoiceDate": "2018-10-24",
    "InvoiceAmount": 2310,
    "Outstanding30Days": 0,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 2310,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221379",
    "ProjectName": "353-9874 Ut St.",
    "ClientName": "Tempus Non Associates",
    "Director": "Le Corbusier",
    "ProjectManager": "Geter Gowan",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001096",
    "InvoiceDate": "2018-10-26",
    "InvoiceAmount": 17050,
    "Outstanding30Days": 0,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 17050,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221423",
    "ProjectName": "Abraj Al-Bait Clock Tower",
    "ClientName": "Et Ultrices Posuere Foundation",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "Harte Melegsalot",
    "InvoiceNumber": "1001103",
    "InvoiceDate": "2018-10-28",
    "InvoiceAmount": 17600,
    "Outstanding30Days": 0,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 17600,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221232",
    "ProjectName": "Bent Pyramid",
    "ClientName": "Phasellus Dolor Elit Industries",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001116",
    "InvoiceDate": "2018-12-03",
    "InvoiceAmount": 3828,
    "Outstanding30Days": 0,
    "Outstanding60Days": 0,
    "Outstanding90Days": 3828,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221265",
    "ProjectName": "Domain West Hollywood",
    "ClientName": "Dolor PC",
    "Director": "Zaha Hadid",
    "ProjectManager": "Brock Lee",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001117",
    "InvoiceDate": "2018-12-03",
    "InvoiceAmount": 5610,
    "Outstanding30Days": 0,
    "Outstanding60Days": 0,
    "Outstanding90Days": 5610,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221423",
    "ProjectName": "Abraj Al-Bait Clock Tower",
    "ClientName": "Et Ultrices Posuere Foundation",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "Harte Melegsalot",
    "InvoiceNumber": "1001120",
    "InvoiceDate": "2018-12-03",
    "InvoiceAmount": 3531,
    "Outstanding30Days": 0,
    "Outstanding60Days": 0,
    "Outstanding90Days": 3531,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221439",
    "ProjectName": "267-6421 Iaculis Rd.",
    "ClientName": "Phasellus Dolor Elit Industries",
    "Director": "Zaha Hadid",
    "ProjectManager": "Justin Case",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001122",
    "InvoiceDate": "2018-12-03",
    "InvoiceAmount": 110000,
    "Outstanding30Days": 0,
    "Outstanding60Days": 0,
    "Outstanding90Days": 110000,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221165",
    "ProjectName": "548-7696 Cursus. Rd.",
    "ClientName": "Malesuada Fames Industries",
    "Director": "Le Corbusier",
    "ProjectManager": "Filet Minyon",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001124",
    "InvoiceDate": "2018-12-03",
    "InvoiceAmount": 4950,
    "Outstanding30Days": 0,
    "Outstanding60Days": 0,
    "Outstanding90Days": 4950,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221165",
    "ProjectName": "548-7696 Cursus. Rd.",
    "ClientName": "Malesuada Fames Industries",
    "Director": "Le Corbusier",
    "ProjectManager": "Filet Minyon",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001138",
    "InvoiceDate": "2018-12-19",
    "InvoiceAmount": 4950,
    "Outstanding30Days": 0,
    "Outstanding60Days": 4950,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "220755",
    "ProjectName": "461-6932 Erat. Rd.",
    "ClientName": "Quisque Tincidunt LLC",
    "Director": "Zaha Hadid",
    "ProjectManager": "Geter Gowan",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001147",
    "InvoiceDate": "2018-12-19",
    "InvoiceAmount": 13794,
    "Outstanding30Days": 0,
    "Outstanding60Days": 13794,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221265",
    "ProjectName": "Domain West Hollywood",
    "ClientName": "Dolor PC",
    "Director": "Zaha Hadid",
    "ProjectManager": "Brock Lee",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001151",
    "InvoiceDate": "2018-12-19",
    "InvoiceAmount": 4708,
    "Outstanding30Days": 0,
    "Outstanding60Days": 4708,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221438",
    "ProjectName": "Machu Picchu",
    "ClientName": "Adipiscing Enim Associates",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001154",
    "InvoiceDate": "2018-12-19",
    "InvoiceAmount": 5500,
    "Outstanding30Days": 0,
    "Outstanding60Days": 5500,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221439",
    "ProjectName": "267-6421 Iaculis Rd.",
    "ClientName": "Phasellus Dolor Elit Industries",
    "Director": "Zaha Hadid",
    "ProjectManager": "Justin Case",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001155",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 18700,
    "Outstanding30Days": 0,
    "Outstanding60Days": 18700,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221049",
    "ProjectName": "The Bartlett, Arlington",
    "ClientName": "Crum Incorporated",
    "Director": "Frank Gehry",
    "ProjectManager": "Filet Minyon",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001167",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 23760,
    "Outstanding30Days": 23760,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221355",
    "ProjectName": "4643 Ligula. Avenue",
    "ClientName": "Ligula Elit Institute",
    "Director": "Frank Wright",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001168",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 11132,
    "Outstanding30Days": 11132,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221436",
    "ProjectName": "Facebook",
    "ClientName": "Jessica O'Brien",
    "Director": "Le Corbusier",
    "ProjectManager": "Dan Druff",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001169",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 6160,
    "Outstanding30Days": 6160,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221165",
    "ProjectName": "548-7696 Cursus. Rd.",
    "ClientName": "Malesuada Fames Industries",
    "Director": "Le Corbusier",
    "ProjectManager": "Filet Minyon",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001170",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 4950,
    "Outstanding30Days": 4950,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221229",
    "ProjectName": "Farm Cultural Park",
    "ClientName": "Lorem Ac Ltd",
    "Director": "Le Corbusier",
    "ProjectManager": "Dan Druff",
    "Supervisor": "Harte Melegsalot",
    "InvoiceNumber": "1001171",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 4664,
    "Outstanding30Days": 4664,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221342",
    "ProjectName": "Metropol Parasol",
    "ClientName": "Dolor Donec Consulting",
    "Director": "Le Corbusier",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001172",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 4125,
    "Outstanding30Days": 4125,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221439",
    "ProjectName": "267-6421 Iaculis Rd.",
    "ClientName": "Phasellus Dolor Elit Industries",
    "Director": "Zaha Hadid",
    "ProjectManager": "Justin Case",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001175",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 8800,
    "Outstanding30Days": 8800,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221423",
    "ProjectName": "Abraj Al-Bait Clock Tower",
    "ClientName": "Et Ultrices Posuere Foundation",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "Harte Melegsalot",
    "InvoiceNumber": "1001176",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 9212.5,
    "Outstanding30Days": 9212.5,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221319",
    "ProjectName": "Lotte World Tower",
    "ClientName": "Diam Inc.",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001177",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 2056.34,
    "Outstanding30Days": 2056.34,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221297",
    "ProjectName": "URBY Staten Island",
    "ClientName": "Leo Morbi PC",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001178",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 4125,
    "Outstanding30Days": 4125,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221232",
    "ProjectName": "Bent Pyramid",
    "ClientName": "Phasellus Dolor Elit Industries",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001180",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 1848,
    "Outstanding30Days": 1848,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "220755",
    "ProjectName": "461-6932 Erat. Rd.",
    "ClientName": "Quisque Tincidunt LLC",
    "Director": "Zaha Hadid",
    "ProjectManager": "Geter Gowan",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001181",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 23210,
    "Outstanding30Days": 23210,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "200066",
    "ProjectName": "315-3542 Tristique Ave",
    "ClientName": "Diam Inc.",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001182",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 4235,
    "Outstanding30Days": 4235,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221172",
    "ProjectName": "4564 Turpis. St.",
    "ClientName": "Dolor PC",
    "Director": "Zaha Hadid",
    "ProjectManager": "Chris P. Bacon",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001184",
    "InvoiceDate": "2019-02-01",
    "InvoiceAmount": 22000,
    "Outstanding30Days": 22000,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221452",
    "ProjectName": "4348 Sed Rd.",
    "ClientName": "Duis Cursus Corporation",
    "Director": "Zaha Hadid",
    "ProjectManager": "Justin Case",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001185",
    "InvoiceDate": "2018-12-19",
    "InvoiceAmount": 33000,
    "Outstanding30Days": 0,
    "Outstanding60Days": 33000,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221379",
    "ProjectName": "353-9874 Ut St.",
    "ClientName": "Tempus Non Associates",
    "Director": "Le Corbusier",
    "ProjectManager": "Geter Gowan",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001186",
    "InvoiceDate": "2019-02-04",
    "InvoiceAmount": 9020,
    "Outstanding30Days": 9020,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "200005",
    "ProjectName": "166-7786 Ut, Ave",
    "ClientName": "Integer Aliquam Incorporated",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001189",
    "InvoiceDate": "2019-02-05",
    "InvoiceAmount": 865.51,
    "Outstanding30Days": 865.51,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "ARMM4D",
    "ProjectName": "3133 Quisque Avenue",
    "ClientName": "Ullamcorper Velit In Limited",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001190",
    "InvoiceDate": "2019-02-05",
    "InvoiceAmount": 452.97,
    "Outstanding30Days": 452.97,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "200555",
    "ProjectName": "8286 In Rd.",
    "ClientName": "Mauris Sapien Cursus LLC",
    "Director": "Zaha Hadid",
    "ProjectManager": "*** Not Defined ***",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001191",
    "InvoiceDate": "2019-02-05",
    "InvoiceAmount": 278,
    "Outstanding30Days": 278,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221457",
    "ProjectName": "Chaoyang Park Plaza",
    "ClientName": "Egestas Fusce Aliquet Incorporated",
    "Director": "Frank Gehry",
    "ProjectManager": "Chris P. Bacon",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "1001192",
    "InvoiceDate": "2019-02-05",
    "InvoiceAmount": 110000,
    "Outstanding30Days": 110000,
    "Outstanding60Days": 0,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221457",
    "ProjectName": "Chaoyang Park Plaza",
    "ClientName": "Egestas Fusce Aliquet Incorporated",
    "Director": "Frank Gehry",
    "ProjectManager": "Chris P. Bacon",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "00001001112A",
    "InvoiceDate": "2018-12-04",
    "InvoiceAmount": 72380,
    "Outstanding30Days": 0,
    "Outstanding60Days": 0,
    "Outstanding90Days": 72380,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221457",
    "ProjectName": "Chaoyang Park Plaza",
    "ClientName": "Egestas Fusce Aliquet Incorporated",
    "Director": "Frank Gehry",
    "ProjectManager": "Chris P. Bacon",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "00001001112B",
    "InvoiceDate": "2018-12-04",
    "InvoiceAmount": 72380,
    "Outstanding30Days": 0,
    "Outstanding60Days": 0,
    "Outstanding90Days": 72380,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  },
  {
    "OrgName": "Unreal Architecture Pty Ltd",
    "ProjectId": "221452",
    "ProjectName": "4348 Sed Rd.",
    "ClientName": "Duis Cursus Corporation",
    "Director": "Zaha Hadid",
    "ProjectManager": "Justin Case",
    "Supervisor": "*** Not Defined ***",
    "InvoiceNumber": "00001001156A",
    "InvoiceDate": "2018-12-19",
    "InvoiceAmount": 27500,
    "Outstanding30Days": 0,
    "Outstanding60Days": 27500,
    "Outstanding90Days": 0,
    "Outstanding120Days": 0,
    "Outstanding120PlusDays": 0
  }
];

export default data;
